services:
  - type: web
    name: gf-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run server
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: RECIPIENT_EMAIL
        sync: false